spring:
  datasource:
    url: jdbc:postgresql://host:port/db
    username: postgres
    password: passwordroot

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: 127.0.0.1
      port: 5379

  session:
    store-type: redis
    timeout: 30m

recaptcha:
  secret: getOneFromGoogle
